GET https://viacep.com.br/ws/95890000/json/

###

GET http://177.44.248.24/pix-api/users/
###

GET http://177.44.248.24/pix-api/pix/31/sent

###

POST http://177.44.248.24/pix-api/pix/
content-type: application/json

{ "senderId": 2, "recipientId": 2, "value": 199.50 }